deploy:
  provider: pypi
  user: wvangeit
  password:
    secure: ESGSWFZxpsIQX9hfJt896J9nsbheP90JGOjr/s8243Lzt+9foLDy83Argn97wynxMcbZeMkIuIqSxDN2WyvgP9glvXi9ef8gmky2Hu8RD7nyPoA74gixguir1x9KcMOS/Lh3LCw5cbL5Xn3Jfng5akVkrdn5kuLPLtOGa72sns15rvjzQLqykDm1ECLAUpCDRby5W6905loxN3RnL0rqrdKIdPZmUkG68b4e95hheI+ZSSYViH4SbANE9GCxM1gzM4Az+DDJRX9nrkM0NyVx/Iq14YPwDOEaUeWMFqXRq/JB/qYI89DFae7TKCHBGy8G/6Dlz+DqpdK9Eto8DU8VLRa/eRa4PANBPoOvLdhIQ8UGoHLQ9G9aQODP5hdPdHtV21wRBZ5MDza1lV3r3+WPrgHN3TYSXlvhqJslWrfwP3ojODOXtITAICQ3jdkh1b/9vIGJNPAg5q5hH5sWtkPFcTTOq0Wdkm+Nyrt7TJlsP451jk0g6jUoN79GWJ1Q+BTpnQQgp+yyKMGSlGW604gTYFeUqmGbnMh9Rp/4vpiCSD1cNEGMXNI7HZN2Fpvqf+boWSJ7Rk6JBy+zUFu23/qG/jXcg/BDOu7CS83GTV53NWyZanRO7MoybBQTHoPuAMRqbGBeOD10jr6fRY6VevpEX9jd5sEK9dAkNG31PPBDDCA=
  on:
    repo: wvangeit/duk
